apiVersion: v1
kind: Service
metadata:
  name: bigid-azure-key-vault-service
spec:
  type: ClusterIP
  selector:
    app: bigid-azure-key-vault
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
